# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Chris Koski
tagline:          'Project Site'
description:      'A site to catalog my projects and such. Kinda like a portfolio. Built on Hyde, which is built on Poole, which is built on Jekyll.'
url:              https://singularity-3.github.io
baseurl:          /singularity-3.github.io

author:
  name:           'Chris Koski'
  url:            https://singularity-3.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet